### ISSUE TITLE
Update obsolete subject headings

### ISSUE THREAD

**Issue by tvirolai** [NatLibFi/marc-record-validators-melinda#11]
A validator is needed for changing obsolete subject headings in records, e.g. headings in YSA that have been changed in the thesaurus after the record has been produced.

A legacy implementation is found [here](https://github.com/NatLibFi/marc-record-validate-legacy-cli/blob/master/ui/validators/SubjectHeadingChange.js). The new validator needs to be configurable. It should accept a configuration object and read the change information from there.

**Comment by tvirolai** [comment]
The new validator should use the Finto API.

**Comment by natlibfi-arlehiko** [comment]
This validator can be used as a reference for using the Finto API: https://github.com/NatLibFi/marc-record-validators-melinda/blob/master/lib/validators/legal-term-factory.js

**Comment by natlibfi-arlehiko** [comment]
Implemented in #50.
