### ISSUE TITLE
isbn-issn: Transform invalid identifiers

### ISSUE THREAD

**Issue by natlibfi-arlehiko** [NatLibFi/marc-record-validators-melinda#36]
# Description
Implement transformation of 020/022 fields which contain invalid ISBN/ISSN
# Speficiation

## First level implementation:

If ISBN from **020 $a** is invalid, move it to **020 $z.**
If ISSN from **022 $a** is invalid, move it to **022 $y**.
If ISSN from **022 $l** is invalid, move it to **022 $y**.  (See: #38) 

## Further implementation:

If a standard number is invalid, and is recognised as valid standard number of an another type, move it to the corresponding field, if record's resource type allows this. 

If a standard number is invalid, but is recognizable as a invalid standard number of certain (one) type, move it to the corresponding invalid standard number field, if record's resource type allows this.

If standard number is invalid, and not recognizable as valid/invalid standard number of any (one) type, move it to a new **024 8_ $a**.

**Comment by natlibfi-arlehiko** [comment]
Specification needed

**Comment by ammsalme** [comment]
If value from f020 $a is invalid as ISBN
- check if it's otherwise valid standard number (currently I

**Comment by natlibfi-arlehiko** [comment]
First level implementation done. Created a new issue for further features in #41
