### ISSUE TITLE
Field structure enhancements

### ISSUE THREAD

**Issue by natlibfi-arlehiko** [NatLibFi/marc-record-validators-melinda#48]
Field structure validator needs the following enhancements:
- **minOccurrance**
  - **Scope**: Field
  - **Type**: Number
  -  **Description**: Defines the minimum number of times the field must occur. Defaults to 1.
- **maxOccurrance**
  -  **Scope**: Field
  - **Type**: Number
  -  **Description**: Defines the maximum number of times the field can occur. Defaults to unlimited.
- **negate**
  -  **Scope**: Dependency
  -  **Type**: Boolean
  -  **Description**: Determines if the rule is negated: No fields can match the dependency specification. Defaults to false.
- **minOccurrance**
  - **Scope**: Dependency
  - **Type**: Number
  -  **Description**: Defines the minimum number of times the field must occur. Defaults to 1.
- **maxOccurrance**
  -  **Scope**: Dependency
  - **Type**: Number
  -  **Description**: Defines the maximum number of times the field can occur. Defaults to unlimited.

**Comment by nu-develop** [comment]
If I can suggest, adding custom error messages would be useful. 

i.e.
```
{
    tag: /^100$/,
    subfields: {
        a: {maxOccurrence: 1}
    },
    msg: 'Subfield $a occurred more than once in tag 100'
}
```

**Comment by natlibfi-arlehiko** [comment]
Not only this validator is lacking descriptive error messages. See #67.

**Comment by natlibfi-arlehiko** [comment]
Continued in internal tracker, if needed
