### ISSUE TITLE
Task "npm run generate-requirejs-config" fails

### ISSUE THREAD

**Issue by tvirolai** [NatLibFi/marc-record-validators-melinda#5]
Running "npm run generate-requirejs-config" npm script fails with the following stacktrace:

> requirejs-configurator --npm -D -P > test/browser-main.js 
Error: Cannot find module 'xmlhttprequest-mock/package.json' from '/home/tvirolai/dev/marc-record-validators-melinda/node_modules/http-client-x-mock'

Error: Cannot find module 'xmlhttprequest-mock/package.json' from '/home/tvirolai/dev/marc-record-validators-melinda/node_modules/http-client-x-mock'
at /home/tvirolai/dev/marc-record-validators-melinda/node_modules/resolve/lib/async.js:46:17
at process (/home/tvirolai/dev/marc-record-validators-melinda/node_modules/resolve/lib/async.js:173:43)
    at ondir (/home/tvirolai/dev/marc-record-validators-melinda/node_modules/resolve/lib/async.js:188:17)
    at load (/home/tvirolai/dev/marc-record-validators-melinda/node_modules/resolve/lib/async.js:69:43)
    at onex (/home/tvirolai/dev/marc-record-validators-melinda/node_modules/resolve/lib/async.js:92:31)
    at /home/tvirolai/dev/marc-record-validators-melinda/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:152:21)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @natlibfi/marc-record-validators-melinda@1.0.2 generate-requirejs-config: `requirejs-configurator --npm -D -P > test/browser-main.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @natlibfi/marc-record-validators-melinda@1.0.2 generate-requirejs-config script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/tvirolai/.npm/_logs/2017-09-04T13_38_43_271Z-debug.log

**Comment by natlibfi-arlehiko** [comment]
Yeah, because of this the browser tests won't run. I'll look into it at some point.

**Comment by natlibfi-arlehiko** [comment]
Obsoleted by new implementation.
