### ISSUE TITLE
Field structure config(present fields)

### ISSUE THREAD

**Issue by nu-develop** [NatLibFi/marc-record-validators-melinda#66]
The description includes a note: "The configured field **don't have to present** in the record but if they are they must conform to the configured structures" . Despite this I'm getting invalid state.
Is it a bug or did I miss something? 

Record:
```
{
  fields: [
    {tag: '001', value: 'bar'}
  ]
}

```
Config:
```
[
  {
    tag: /^005$/,
    valuePattern: /bar/
  }
]
```

Report:
```
{ description: 'Check whether the configured fields have valid structure',
    state: 'invalid',
    messages: undefined }
```

**Comment by natlibfi-arlehiko** [comment]
Please make sure you are using the latest version of marc-record-validators-melinda. This issue was fixed in an earlier version.

**Comment by nu-develop** [comment]
It's strange because I'm using the latest version(5.1.0). I think the reason is here:
```
const foundFields = record.get(searchedField);
// If data matching configuration is not found
if (foundFields.length === 0) {
    return false;
}
```
If I understand correctly, when foundFields.length === 0 there is nothing to validate and should return true. Correct me if I'm wrong.

**Comment by natlibfi-arlehiko** [comment]
Yes. This was a bug I just fixed it (2ef3f33788cb7b9043023d84fe183b2e41adb7d4) and updated the documentation. Fields are however required even if their dependencies match but that's not the case in your example.

I canẗ upload the new version to NPM right now, but I'll do it later this week.

**Comment by natlibfi-arlehiko** [comment]
New version (5.1.1) is now published

**Comment by nu-develop** [comment]
Thanks for fixing.
