### ISSUE TITLE
ISBN/ISSN: Better validation

### ISSUE THREAD

**Issue by natlibfi-arlehiko** [NatLibFi/marc-record-validators-melinda#79]
By default, this validator should check for existence of a/l-subfields of 020/022-fields. If the subfield scannot be found the record should be set as invalid (Cannot be fixed).

If the subfields are found the identifier should be validated. If only missing hyphens, the record should be set as invalid, but can be fixed (By adding the hyphens).

An optional setting should be implemented that triggers using the **z**-subfield. If this the previously mentioned subfields are not found but this subfield is, then the record is set as valid. If the the previously mentioned subfields are found but the identifier is invalid, the record should be set as invalid, but can be fixed by moving the invalid identifier to the **z**-subfield.

**Comment by natlibfi-jonollil** [comment]
Separate changes to two commits: Style and dependency -specific changes and isbn-related changes to to their own commits (Can be done with git-rebase and the force pushing to this branch).
    Implement a new option that can be enabled to set the record as invalid when 020 and 022 fields are missing.

**Comment by natlibfi-jonollil** [comment]
In field 022 transfering invalid issn value to subfield y as https://marc21.kansalliskirjasto.fi/bib/01X-04X.htm#022 says

**Comment by natlibfi-jonollil** [comment]
New validation option is called saveInvalidIsbnIssnValues
